### PR TITLE
removed deploy-variables article.

### PR DESCRIPTION
**Pull request by flenter**
Content already exists at: /docs/environment-variables/available-env-vars.html

### CODE REVIEW

**Comment by mies** [comment]
:100:

**Comment by hatchan** [comment]
Please update references to this removed file

**Comment by flenter** [comment]
I looked for `docs/environment-variables/deploy-variables` and `docs/steps/deploy-env-vars` but that didn't exist (as well as `deploy-env-vars` and `deploy-variables`), what did I miss?

**Comment by hatchan** [comment]
Latest spider result showed this (where the second is not relevant):

```
Found 2 broken links.

http://devcenter.wercker.com/docs/environment-variables/deploy-variables.html
http://devcenter.wercker.com/docs/environment-variables/using-env-vars.html
```

**Pull request merged**
