### PR TITLE
Update for ewok caching

### PR DESCRIPTION
**Pull request by Tonnu**
Small changes

### CODE REVIEW

**Comment by joepjoosten** [comment]
Are you sure this is working for the ewok platform? I see in my build using maven and the wercker cache dir, e.g.

    mvn clean package -Dmaven.repo.local=$WERCKER_CACHE_DIR/.m2

But it keeps redownloading every dependency every build...
(downloaded dependencies approx. 125 Mb.)

**Comment by hatchan** [comment]
We're in the process of releasing this feature, it's not yet released though

**Comment by joepjoosten** [comment]
That explains...

**Comment by joepjoosten** [comment]
Any timeline for this release?

**Comment by hatchan** [comment]
We're hoping to do a release tomorrow, otherwise it will be released next week

**Comment by Tonnu** [comment]
Caching has been merged in, docs can go live as well.

**Comment by Starefossen** [comment]
Hmm... I'm running into what is probably an error with the cache when running `npm-install`. It can't find newly published versions in the registry after a cache clear.

**Comment by hatchan** [comment]
@Starefossen Currently the cache clear isn't working for the new stack caching. We're going to release the fix for that today.

I've noticed the latest builds are green, so I'm assuming it was a temporary issue?

**Comment by Starefossen** [comment]
I temporarily replacing `npm-install` with a script calling `npm install` to avoided caching. Will revert this now since we have cache clear for ewok :smile:

**Comment by hatchan** [comment]
Cache clearing is now working for the ewok stack

**Comment by Starefossen** [comment]
:clap:

**Pull request merged**
