### PR TITLE
Add title

### PR DESCRIPTION
**Pull request by flenter**
searches the page for first h1, h2,h3,h4,h5 and finally h6 on the page to append to page title.

### CODE REVIEW

**Comment by lindseybateman** [comment]
cool!
what will happen on index/index.html?
<title>wercker - dev center</title> alone will be enough right?

**Comment by flenter** [comment]
Things go wrong if the page contains no header at all. Do we have pages without any headers?

**Comment by flenter** [comment]
Earlier I tried to do a handlebars like if statement, but we're using moustache here... so that doesn't work.I've added the if statement, the moustache way.

**Comment by lindseybateman** [comment]
i think al pages have headers

**Pull request merged**
