### PR TITLE
Run docs through spell-check and normalize style

### PR DESCRIPTION
**Pull request by mwhooker**
I ran the docs through a spell checker, since we've been getting a lot of spelling PRs.

In the process I realized we needed to standardize a few things, so I wrote a quick style guide and implemented the guide. Please have a look, especially @mies, and let me know what everyone thinks.

### CODE REVIEW

**Comment by mies** [comment]
I like this! Happy to merge this in (the build is broken though). After this we can start expanding on other conventions and adding to the exception list.

**Comment by mwhooker** [comment]
@lauraakelso I would definitely consider "workflow" acceptable as a term of art. 

@mies not sure why build is failing. it doesn't seem to be related to these changes

**Comment by flenter** [comment]
The build needs to be rebased. An update to npm/dependency caused master to break, the fix has been merged in (pr #287)

**Comment by Tonnu** [comment]
Rebased this on master, will merge in shortly

**Pull request merged**
