### PR TITLE
Linkcheck

### PR DESCRIPTION
**Pull request by mwhooker**
We often get reports of broken links:
#267
#261
#256
etc.

Want to fix these forever by automating the checks.

### CODE REVIEW

**Comment by mwhooker** [comment]
I don't think it's actually running the checkLinks step...

**Comment by mwhooker** [comment]
Okay, this works. The test failure in https://app.wercker.com/#buildstep/55cea3b0b006c1f91e00ad9c proves it

Ready for review

**Comment by mwhooker** [comment]
might be cool to make this in to a step...

**Comment by Tonnu** [comment]
lgtm, step would be nice

**Comment by hatchan** [comment]
:+1:

**Pull request merged**
